# Import & Matrix Definition

In [ ]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

# Direct 3x3 Student Data Matrix (NO mean centering)
A = np.array([
    [2, 1, -1],
    [3, 2, -3],
    [3, 1, -2]
], dtype=float)

print("Matrix A (Original Data Matrix):\n", A)


Matrix A (Original Data Matrix):
 [[ 2.  1. -1.]
 [ 3.  2. -3.]
 [ 3.  1. -2.]]


#Symbolic Form of (A − λI)

In [ ]:
print("Symbolic representation of (A - λI):\n")
print("[ 2-λ   1     -1 ]")
print("[ 3    2-λ   -3 ]")
print("[ 3     1   -2-λ ]")


Symbolic representation of (A - λI):

[ 2-λ   1     -1 ]
[ 3    2-λ   -3 ]
[ 3     1   -2-λ ]


# Characteristic Polynomial ∣𝜆𝐼−𝐴∣=0

In [ ]:
# Get coefficients of characteristic polynomial
coeffs = np.poly(A)

print("Characteristic Polynomial Coefficients:")
print(coeffs)

print("\nCharacteristic Polynomial:")
print(f"λ³ - {abs(coeffs[1]):.0f}λ² + {coeffs[2]:.0f}λ - {abs(coeffs[3]):.0f} = 0")


Characteristic Polynomial Coefficients:
[ 1. -2. -1.  2.]

Characteristic Polynomial:
λ³ - 2λ² + -1λ - 2 = 0


# Eigenvalues & Eigenvectors Using NumPy

In [ ]:
eigen_values, eigen_vectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigen_values)

print("\nEigenvectors (Each column is one eigenvector):")
print(eigen_vectors)


Eigenvalues:
[-1.  2.  1.]

Eigenvectors (Each column is one eigenvector):
[[ 0.       -0.57735   0.707107]
 [-0.707107 -0.57735  -0.      ]
 [-0.707107 -0.57735   0.707107]]


# Eigenvector - Math process

In [ ]:
def nullspace_vector(M):
    # SVD method to extract nullspace
    U, S, Vt = np.linalg.svd(M)
    v = Vt[-1]
    v = v / np.linalg.norm(v)
    return v


# Step-by-Step Eigenvector Computation for EACH λ

In [ ]:
for i, lam in enumerate(eigen_values):
    print(f"\nEigenvalue λ{i+1} = {lam:.6f}")

    # Form (A - λI)
    M = A - lam * np.eye(3)
    print("\n(A - λI) =\n", M)

    # Solve (A - λI)v = 0
    v = nullspace_vector(M)

    # Normalize for clean display
    idx = np.argmax(np.abs(v))
    if v[idx] < 0:
        v = -v
    v = v / np.linalg.norm(v)

    print("\nComputed Eigenvector v =")
    print(v)




Eigenvalue λ1 = -1.000000

(A - λI) =
 [[ 3.  1. -1.]
 [ 3.  3. -3.]
 [ 3.  1. -1.]]

Computed Eigenvector v =
[0.       0.707107 0.707107]

Eigenvalue λ2 = 2.000000

(A - λI) =
 [[ 0.  1. -1.]
 [ 3.  0. -3.]
 [ 3.  1. -4.]]

Computed Eigenvector v =
[0.57735 0.57735 0.57735]

Eigenvalue λ3 = 1.000000

(A - λI) =
 [[ 1.  1. -1.]
 [ 3.  1. -3.]
 [ 3.  1. -3.]]

Computed Eigenvector v =
[0.707107 0.       0.707107]
